name: github pages

on:
  push:
    branches:
    - master
  repository_dispatch:
    types: [trigger-action-by-content]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.0.0

    - name: Checkout content submodule
      uses: actions/checkout@v2.0.0
      with:
        repository: winwangqi/notebook_website_content
        path: content
        ref: 'master'

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.15.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install

    - run: npm run clean

    - run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        EXTERNAL_REPOSITORY: winwangqi/winwangqi.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
